import type {Feature,Polygon,Point} from 'geojson';
export type Mode='pressure'|'activity'|'land'|'age'|'transit'|'renters'|'protection'|'matrix'; export type Weights={activity:number;policy:number;land:number;age:number;transit:number}; export type Permit={permit_number:string;issue_date:string;type:string;address:string;description:string;source_url:string};
export type Parcel={parcel_id:string;pid:string|null;address:string;lon:number;lat:number;year_built:number|null;land_value:number|null;improvement_value:number|null;land_improvement_ratio:number|null;assessment_year:number|null;assessment_record_count:number;current_zoning:string|null;zoning_classification:string|null;distance_station_m:number;nearest_station:string;within_400m:boolean;within_800m:boolean;rental_status:string;existing_rental_units:number|null;renter_exposure_score:number|null;renter_exposure_status:string;trpp_status:string;enhanced_protection_context:string;permits:Permit[];permit_count:number;last_permit_year:number|null;development_activity_score:number;policy_potential_score:number|null;policy_potential_status:string;building_age_score:number|null;land_value_score:number|null;station_proximity_score:number;redevelopment_pressure_score:number|null;pressure_data_completeness:number;exposure_category:string;source_metadata:{confidence:string;spatial_precision:string;manual_verification:boolean};data_status:string};
export type Dataset={type:'FeatureCollection';metadata:{generated_utc:string;study_extent_status:string;study_extent_note:string;claims:string};stations:Feature<Point,{name:string;source:string;source_url:string;status:string}>[];study_extent:{type:'Polygon';coordinates:number[][][]};features:Feature<Polygon,Parcel>[]}; export type Settings={mode:Mode;station:string;radius:number;status:string;minYear:number;minPressure:number;weights:Weights};
export const defaults:Settings={mode:'pressure',station:'All stations',radius:800,status:'all',minYear:0,minPressure:0,weights:{activity:30,policy:25,land:20,age:15,transit:10}}; export const modeNames:Record<Mode,string>={pressure:'Redevelopment pressure',activity:'Issued permit activity',land:'Land-value intensity',age:'Building age',transit:'Future subway proximity',renters:'Existing renter exposure',protection:'Tenant protection context',matrix:'Renter × pressure matrix'};
export function readSettings(search:string):Settings{const p=new URLSearchParams(search);const mode=Object.hasOwn(modeNames,p.get('mode')||'')?p.get('mode') as Mode:'pressure';const num=(k:string,d:number,min:number,max:number)=>{const n=Number(p.get(k));return p.has(k)&&Number.isFinite(n)?Math.max(min,Math.min(max,n)):d};return{mode,station:(p.get('station')||'All stations').slice(0,80),radius:[400,800,1200].includes(num('radius',800,400,1200))?num('radius',800,400,1200):800,status:['all','demolition','new construction','major alteration'].includes(p.get('status')||'')?p.get('status')!:'all',minYear:num('minYear',0,0,2026),minPressure:num('minPressure',0,0,100),weights:{activity:num('wActivity',30,0,100),policy:num('wPolicy',25,0,100),land:num('wLand',20,0,100),age:num('wAge',15,0,100),transit:num('wTransit',10,0,100)}}}
export function query(s:Settings){return new URLSearchParams({mode:s.mode,station:s.station,radius:String(s.radius),status:s.status,minYear:String(s.minYear),minPressure:String(s.minPressure),wActivity:String(s.weights.activity),wPolicy:String(s.weights.policy),wLand:String(s.weights.land),wAge:String(s.weights.age),wTransit:String(s.weights.transit)}).toString()}
export function pressure(p:Parcel,w:Weights){const pairs:[number|null,number][]=[[p.development_activity_score,w.activity],[p.policy_potential_score,w.policy],[p.land_value_score,w.land],[p.building_age_score,w.age],[p.station_proximity_score,w.transit]];const required=pairs.filter(([,weight])=>weight>0);if(required.some(([v])=>v===null)||!required.length)return null;const total=required.reduce((s,[,weight])=>s+weight,0);return required.reduce((s,[v,weight])=>s+v!*weight,0)/total}
export function value(p:Parcel,mode:Mode,w:Weights){if(mode==='pressure')return pressure(p,w);if(mode==='activity')return p.development_activity_score;if(mode==='land')return p.land_value_score;if(mode==='age')return p.building_age_score;if(mode==='transit')return p.station_proximity_score;return null}
export function filtered(p:Parcel,s:Settings){const score=pressure(p,s.weights);return(s.station==='All stations'||p.nearest_station===s.station)&&p.distance_station_m<=s.radius&&(s.status==='all'||p.permits.some(x=>x.type===s.status))&&(!s.minYear||(p.last_permit_year??0)>=s.minYear)&&(score===null?s.minPressure===0:score>=s.minPressure)}
export const colour=(v:number|null)=>v===null?'#a6ada9':v<20?'#e8e4d7':v<40?'#d7c79a':v<60?'#d79762':v<80?'#bd5a49':'#792f3a'; export const money=(v:number|null)=>v===null?'Unknown':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(v);
export function csv(features:Feature<Polygon,Parcel>[],s:Settings){const h=['parcel_id','pid','address','nearest_station','distance_station_m','year_built','current_zoning','land_value','improvement_value','land_improvement_ratio','permit_count','last_permit_year','rental_status','existing_rental_units','renter_exposure_score','trpp_status','redevelopment_pressure_score','data_status'];const rows=[h,...features.map(f=>{const p=f.properties;return[p.parcel_id,p.pid,p.address,p.nearest_station,p.distance_station_m,p.year_built,p.current_zoning,p.land_value,p.improvement_value,p.land_improvement_ratio,p.permit_count,p.last_permit_year,p.rental_status,p.existing_rental_units,p.renter_exposure_score,p.trpp_status,pressure(p,s.weights)?.toFixed(1)??'',p.data_status]})];return rows.map(r=>r.map(v=>'\"'+String(v??'').replaceAll('\"','\"\"')+'\"').join(',')).join('\r\n')}
